name: Test tree-sitter bindings

on:
  push:

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    env:
      CC: gcc
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout spavn-analyzer
        uses: actions/checkout@v3
        with:
          path: spavn-analyzer
      - name: Install dependencies
        run: |
          mkdir -p ./spavn-analyzer/modules
          git clone https://github.com/nedpals/vex ./spavn-analyzer/modules
      - name: Run tests
        run: |
          cd spavn-analyzer/tree_sitter
          v test .

  test-macos:
    runs-on: macos-latest
    env:
      CC: clang
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout spavn-analyzer
        uses: actions/checkout@v3
        with:
          path: spavn-analyzer
      - name: Install dependencies
        run: |
          mkdir -p ./spavn-analyzer/modules
          git clone https://github.com/nedpals/vex ./spavn-analyzer/modules
      - name: Compile
        run: |
          cd spavn-analyzer/tree_sitter
          v test .

  test-windows:
    runs-on: windows-latest
    env:
      CC: msvc
    steps:
      - uses: msys2/setup-msys2@v2
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout spavn-analyzer
        uses: actions/checkout@v3
        with:
          path: spavn-analyzer
      - name: Compile
        run: |
          cd spavn-analyzer/tree_sitter
          v test .
